---
title: "Pablo Hidalgo CV"
author: Pablo Hidalgo García
output: pagedown::html_resume
---


Aside
====================================


Información de contacto
------------------------------------

<i class="fa fa-envelope"></i> pablohigar@gmail.com

<i class="fa fa-phone"></i> 675 83 82 79

<i class="fa fa-github"></i> github.com/papabloblo

Skills
------------------------------------

- R
- Python
- Spark
- Shiny
- Machine Learning (regresión lineal, árboles de decisión, boosting, random forest, ...)
- SAS
- git
- Linux
- Visualización de datos (ggplot2, D3) 
- English (B2)



Main
====================================

Pablo Hidalgo García {#title}
------------------------------------

Apasionado del **data science**, de la **visualización de datos**, de **R** y de la **docencia**. Convencido de que los algoritmos no sirven para nada si no somos capaces de comunicarlos hacia aquellos que van a utilizarlos o, al menos, ayudar a entender sus resultados.

Comencé trabajando con tecnología **SAS** implementando algoritmos heurísticos para encontrar la mejor planificación horaria de los empleados de una gran empresa de retail. Poco a poco, conseguí orientar mi carrera hacia el uso de tecnología **R** y **Python** participando en proyectos como la **estimación de la demanda** para el sector energético, **predicción de baja de clientes**, **agrupación de comportamientos de consumo** eléctrico hasta llegar a liderar la parte técnica de un proyecto de **optimización de precios** para una empresa de retail.

Durante el 2017, Innova-tsn decidió crear un laboratorio de innovación analítica que perseguía ser la referencia técnica dentro de la compañía y desarrollar soluciones mediante software *open source* en el que trabajé como responsable.

He impartido cursos de formación tanto en **Innova-tsn** como a través de la escuela **MSMK**. Estos cursos han sido, principalmente, de modelización estadística, software R, bases de datos (SQL y NoSQL) y visualización siendo tanto cursos aislados como contenidos dentro de diversos másteres y grados.



Experiencia profesional {data-icon=chalkboard-teacher}
------------------------------------

### Senior Data Scientist

Innova-tsn

Madrid

2016-2019

Responsable del laboratorio de innovación analítica. Desarrollo de soluciones con tecnología Open Source (R y Python, fundamentalmente).

Responsable analítico de la implementación de una solución para la optimización de precios.

Asesoramiento de soluciones técnicas en proyectos de predicción de la demanda, predicción de audiencias y fuga de clientes

Impartición de cursos de modelización estadística y programación en R.

### Data scientist

Innova-tsn

Madrid

2014-2016

Optimización del horario de los empleados de una gran compañía retail.

Agrupación de curvas de consumo para el sector energético.

Cursos de formación de SAS.


Experiencia académica {data-icon=chalkboard-teacher}
------------------------------------
### Profesor asociado de Minería de datos

Universidad Francisco de Vitoria (UFV)

Madrid

2019-2020

Grado en Business Analytics

### Asignatura de Data Analytics (52 horas)

Grado en Business (MSMK)

Madrid

03-06/2019


### Taller de bases de datos NoSQL (6 horas)

Máster en Business Analytics y Data Strategy (MSMK)

Madrid

12/2018

### Módulo 1: el origen del Big Data (30 horas)

Máster en Advance Analytics y Cognitive Inteligence (MSMK)

Madrid

12/2018

### Taller de bases de datos relacionales (6 horas)

Máster en Business Analytics y Data Strategy (MSMK)

Madrid

10/2018

### Introducción a la programación en R (15 horas)

MSMK

Madrid

10/2018

### Taller de visualización de datos (3 horas)

Máster en Business Analytics y Data Strategy (MSMK)

Madrid

6/2018

### Taller de bases de datos SQL y NoSQL (6 horas)

Máster en Business Analytics y Data Science (MSMK)

Madrid

6/2018

### Introducción a la programación en R (15 horas)

MSMK

Madrid

06/2018

### Introducción a la programación en R (20 horas)

Mediaset

Madrid

01/2018



Ponencias {data-icon=chalkboard-teacher}
------------------------------------

### Inteligencia artificial y visualización de datos

MSMK

Madrid

11/2018

La importancia de la visualización de datos para **entender** los resultados de los algoritmos de Inteligencia Artificial.

### Semiboost: un paquete para el aprendizaje semisupervisado.

IX Jornadas de Usuarios de R

Granada

11/2017


### Teoría de cópulas aplicada a la optimización de precios

VIII Jornadas de Usuarios de R

Granada

11/2017




Educación {data-icon=graduation-cap}
------------------------------------

### Máster universitario en investigación en inteligencia artificial

Universidad Internacional Menéndez Pelayo (UIMP)

Madrid

2019-2020

### Grado en matemáticas y estadística

Universidad Complutense de Madrid (UCM)

Madrid

2009-2014


### English Upper-intermediate (B2.1)

British Council, Universidad de Alcalá de Henares (UAH).

Alcalá de Henares

2013


### Análisis de datos estadísticos con SAS

Escuela Complutense de Verano

Madrid 

2013



### Stat2.1x: Introduction to Statistics: Descriptive Statistics

BerkeleyX

edX

2013


### Stat2.2x: Introduction to Statistics: Probability

BerkeleyX

edX

2013


